<div id="approvedoffermessage_container_bg" onclick="javascript:hideMessageBox()" style="display: none; background-color: #fff; top: 0pt; left: 0pt; width: 100%; height: 100%; position: fixed; z-index: 10; opacity: 0.5;"></div>
<div id="approvedoffermessage_container" style="display:none; margin-top: 50px; position: fixed; z-index: 50; left: 50%; top: 40%; background: none repeat scroll 0 0 #fff; padding: 40px; border: 4px double orange;">
	<div id="approvedoffermessage_container_close_button" onclick="javascript:hideMessageBox()" style=""><?php echo $this->__("CLOSE [X]") ?></div>
	<div id="approvedoffermessage_container_message"></div>
</div>